### PR TITLE
Refactor tests, improve formatting and documentation

### PR DESCRIPTION
**Pull request by geek1011**
This PR refactors the tests to:
- Be more complete.
- Fail randomly to test retries.
- Check the request method.
- Be more concise.

In addition, there are various formatting improvements (to match standard Go style as documented [here](https://golang.org/doc/effective_go.html#formatting), especially around spacing of code blocks for error handling) and documentation improvements (also to match Go style, mainly proper sentence structure and periods).

### CODE REVIEW

**Comment by ddymko** [comment]
@geek1011 

I took a quick look at this and I do have some reservations mainly being how others on the team feel about taking this approach. I don't want you to spend more time on this if the team as a whole feels that the current structure should be maintained the way it is or not.

Let me have an internal discussion about this with the team here

**Comment by geek1011** [comment]
@ddymko, Sounds good. All that's really left (and also happens to be the most tedious and time-consuming part) is to finish converting and testing the other endpoints, improve the docs for each one, replace the mux.HandleFunc in each test, and then remove the old request code.

**Comment by ddymko** [comment]
@geek1011 

We reviewed the changes and we decided to stick with the current design we have implemented. 

We do have a V2 of our current API planned in our pipeline. This would make our API more resftful and remove some of the nuances we currently have with V1. Once V2 is out we will need to revisit this go client so we may look into your set of changes as a good design for V2.

We appreciate the effort you put into this far and still welcome the formatting improvements you mentioned!

**Comment by geek1011** [comment]
OK, thanks for letting me know ahead of time. I'll revert the API changes, but keep the unit test, grammar, and formatting improvements.

**Comment by geek1011** [comment]
I haven't had a chance to work on this yet, and it's getting stale, so I'm going to close this for now and open a new one if I work on this in the future.

**Pull request closed without merging**
