### PR TITLE
Change tag to *string on update reqs

### PR DESCRIPTION
**Pull request by optik-aper**
## Description

Change the update req structs so that `tag` can be deleted by sending an empty string.  Previously empty was ignored.
## Related Issues

#221 

### Checklist:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linted your code locally prior to submission?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by optik-aper** [comment]
## Testing
### Instance
* Create an instance:

	  func instCreate(client *govultr.Client, ctx context.Context) {
		  inst, err := client.Instance.Create(ctx, &govultr.InstanceCreateReq{
			  Region: "ewr",
			  Plan:   "vc2-1c-1gb",
			  Label:  "inst-z1",
			  OsID:   244,
		  })
		  if err != nil {
			  fmt.Println(err)
			  panic(err.Error())
		  }
  
		  fmt.Println(inst)
	  }

	
* Add a `Tag` to the instance as a `*string`:

	  func instUpdate(client *govultr.Client, ctx context.Context) {
  
		  instID := "<UUID>"
  
		  inst, err := client.Instance.Update(ctx, instID, &govultr.InstanceUpdateReq{
			  Tag: govultr.StringToStringPtr("test2"),
		  })
  
		  if err != nil {
			  fmt.Println(err)
			  panic(err.Error())
		  }
  
		  fmt.Println(inst)
	  }

* Check the output for the new tag
* Clear out `Tag` by sending an empty `*string`:

	  func instUpdate(client *govultr.Client, ctx context.Context) {
  
		  instID := "<UUID>"
  
		  inst, err := client.Instance.Update(ctx, instID, &govultr.InstanceUpdateReq{
			  Tag: govultr.StringToStringPtr(""),
		  })
  
		  if err != nil {
			  fmt.Println(err)
			  panic(err.Error())
		  }
  
		  fmt.Println(inst)
	  }

* Check again and make sure `tag` is blank
### Bare Metal
* Create a server:

	  func bmCreate(client *govultr.Client, ctx context.Context) {
		  bm, err := client.BareMetalServer.Create(ctx, &govultr.BareMetalCreate{
			  Region: "lax",
			  Plan:   "vbm-4c-32gb",
			  Label:  "bm-x1",
			  OsID:   477,
		  })
  
		  if err != nil {
			  fmt.Println(err)
			  panic(err.Error())
		  }
  
		  fmt.Println(bm)
	  }
	
* Add a `Tag` to the server as a `*string`:
  
	  func bmUpdate(client *govultr.Client, ctx context.Context) {
  
		  bmID := "<UUID>"
  
		  bm, err := client.BareMetalServer.Update(ctx, bmID, &govultr.BareMetalUpdate{
			  Tag: govultr.StringToStringPtr("test-tag"),
		  })
  
		  if err != nil {
			  fmt.Println(err)
			  panic(err.Error())
		  }
  
		  fmt.Println(bm)
	  }

* Check for the `tag` in the output
* Clear out the `Tag` by sending an empty `*string`:

	  func bmUpdate(client *govultr.Client, ctx context.Context) {
  
		  bmID := "<UUID>"
  
		  bm, err := client.BareMetalServer.Update(ctx, bmID, &govultr.BareMetalUpdate{
			  Tag: govultr.StringToStringPtr(""),
		  })
  
		  if err != nil {
			  fmt.Println(err)
			  panic(err.Error())
		  }
  
		  fmt.Println(bm)
	  }

* Check again and make sure the `tag` is blank

### VKE
* Create a cluster:

	  func vkeClusterCreate(client *govultr.Client, ctx context.Context) {
  
		  cluster, err := client.Kubernetes.CreateCluster(ctx, &govultr.ClusterReq{
			  Region:  "lax",
			  Label:   "cluster-iv",
			  Version: "v1.23.5+3",
			  NodePools: []govultr.NodePoolReq{
				  {
					  NodeQuantity: 1,
					  Plan:         "vc2-2c-4gb",
					  Label:        "np-i",
				  },
			  },
		  })
  
		  if err != nil {
			  fmt.Println(err)
			  panic(err.Error())
		  }
  
		  fmt.Println(cluster)
	  }

* Lookup cluster and node pool UUIDs:

	  func vkeClusterGet(client *govultr.Client, ctx context.Context) {
		  var clusterID string = "<UUID>"
		  cluster, err := client.Kubernetes.GetCluster(ctx, clusterID)
  
		  if err != nil {
			  fmt.Println(err)
			  panic(err.Error())
		  }
  
		  fmt.Println(cluster)
	  }
	  
* Update the node pool and add a `Tag`:

	  func vkeNodePoolUpdate(client *govultr.Client, ctx context.Context) {
		  var clusterID string = "<UUID>"
		  var nodePoolID string = "<UUID"
		  np, err := client.Kubernetes.UpdateNodePool(ctx, clusterID, nodePoolID, &govultr.NodePoolReqUpdate{
			  Tag: govultr.StringToStringPtr("test-tag"),
		  })
  
		  if err != nil {
			  fmt.Println(err)
			  panic(err.Error())
		  }
  
		  fmt.Prinln(np)
	  }

* Check the output and make sure the tag exists
* Clear out the `Tag` by sending an empty `*string`:

	  func vkeNodePoolUpdate(client *govultr.Client, ctx context.Context) {
		  var clusterID string = "<UUID>"
		  var nodePoolID string = "<UUID>"
		  np, err := client.Kubernetes.UpdateNodePool(ctx, clusterID, nodePoolID, &govultr.NodePoolReqUpdate{
			  Tag: govultr.StringToStringPtr(""),
		  })
  
		  if err != nil {
			  fmt.Println(err)
			  panic(err.Error())
		  }
  
		  fmt.Prinln(np)
	  }

* Make sure `tag` is blank in the output

**Comment by ddymko** [comment]
Everything is working expect for VKE - we'll have to update the API to support the behavior. Holding this until the API updates go out

**Comment by optik-aper** [comment]
Commit [fbb7899](https://github.com/vultr/govultr/pull/222/commits/fbb789996a8d358cd7147726f161344cf9794b46) updates the `tag` field on update calls to "omitempty" so that we don't send `null` in the body when the value is undefined.  It also changes the `auto_scaler` type to "omitempty" as well for the same reason.

## Testing
### `Tag`
There are three test cases:
* Where `Tag` has an actual tag in the update
* `Tag` is deleting the tag value with `""`
* And `Tag` is not sent in the update

#### With tag

On **node pools**:

	func vkeNodePoolUpdate(client *govultr.Client, ctx context.Context) {
		var clusterID string = "ec9c6ba7-5182-4fcd-8091-d5e65f677dfa"
		var nodePoolID string = "963a698c-1270-4411-ae19-af2fb0f17ccb"
		np, err := client.Kubernetes.UpdateNodePool(ctx, clusterID, nodePoolID, &govultr.NodePoolReqUpdate{
			Tag: govultr.StringToStringPtr("test-tag"),
		})

		if err != nil {
			fmt.Println(err)
			panic(err.Error())
		}

		printJson(np)
	}

Which generates a request body:

	{"tag":"test-tag"}

And updates the tag as expected:

	{
		"id": "963a698c-1270-4411-ae19-af2fb0f17ccb",
		"date_created": "2022-05-16T19:31:11+00:00",
		"date_updated": "2022-05-17T13:44:46+00:00",
		"label": "np-tag-reset",
		"plan": "voc-c-2c-4gb-75s-amd",
		"status": "active",
		"node_quantity": 3,
		"min_nodes": 1,
		"max_nodes": 1,
		"auto_scaler": false,
		"tag": "test-tag",
		"nodes": [
			{
				"id": "af4830f3-1886-4434-ad12-43849e24b3a3",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-584bd1ebbf15",
				"status": "active"
			},
			{
				"id": "7c52abc0-5bcd-494f-ba54-b57989fbe1f5",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-90b3ae63f540",
				"status": "active"
			},
			{
				"id": "48b42054-d099-49e1-8900-b7e4ef46f976",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-e31a47a6fcd8",
				"status": "active"
			}
		]
	}
	
On **instances**:

	func instUpdate(client *govultr.Client, ctx context.Context) {

		instID := "9c89193b-21af-4269-9212-96d7acb19145"

		inst, err := client.Instance.Update(ctx, instID, &govultr.InstanceUpdateReq{
			Tag: govultr.StringToStringPtr("test-tag"),
		})

		if err != nil {
			fmt.Println(err)
			panic(err.Error())
		}

		printJson(inst)
	}

Which generates this body:

	{"tag":"test-tag","tags":null,"ddos_protection":null}

And updates the tag as expected:

	{
		"id": "9c89193b-21af-4269-9212-96d7acb19145",
		"os": "Debian 11 x64 (bullseye)",
		"ram": 1024,
		"disk": 0,
		"plan": "vc2-1c-1gb",
		"main_ip": "108.61.86.208",
		"vcpu_count": 1,
		"region": "ewr",
		"date_created": "2022-05-16T16:20:53+00:00",
		"status": "active",
		"allowed_bandwidth": 1000,
		"netmask_v4": "255.255.254.0",
		"gateway_v4": "108.61.86.1",
		"power_status": "running",
		"server_status": "ok",
		"v6_network": "",
		"v6_main_ip": "",
		"v6_network_size": 0,
		"label": "testest",
		"internal_ip": "",
		"kvm": "https://my.vultr.com/subs/vps/novnc/api.php?data=djJ8dVF2TEF6SUZGd2FYZnBRalkwV2tPam5oQk1rSjFKQmV8kV-Ofe4U6-tqKMpsdHYdWcbPTn_O_NP3cjOxdgWGYri3ppITVHqg54DzWjpj7mClzSf6VCjZ-qGRuNshzS7lJAFkUt1AypcKvDNXROfGTrqDFgxB26SbK285gwCKujdfcNXfV_UyKyReG_cl2PFE9mm5KCcFylBTXqDVOxJdbAJU9k-AoC7r7gxjIY2kTdEZrA5T-39QX9OY",
		"tag": "test-tag",
		"os_id": 477,
		"app_id": 0,
		"image_id": "",
		"firewall_group_id": "",
		"features": [],
		"hostname": "vultr.guest",
		"tags": []
	}

On **bare metal**:

	func bmUpdate(client *govultr.Client, ctx context.Context) {

		bmID := "7ea675a7-db61-40cc-aa68-9135ead25352"

		bm, err := client.BareMetalServer.Update(ctx, bmID, &govultr.BareMetalUpdate{
			Tag: govultr.StringToStringPtr("test-tag"),
		})

		if err != nil {
			fmt.Println(err)
			panic(err.Error())
		}

		printJson(bm)
	}

Which generates this request body:

	{"tag":"test-tag","tags":null}

And updates the tag as expected:

	{
		"id": "7ea675a7-db61-40cc-aa68-9135ead25352",
		"os": "Debian 11 x64 (bullseye)",
		"ram": "32768 MB",
		"disk": "2x 240GB SSD",
		"main_ip": "149.248.9.242",
		"cpu_count": 4,
		"region": "lax",
		"default_password": "",
		"date_created": "2022-05-17T14:10:02+00:00",
		"status": "pending",
		"netmask_v4": "255.255.254.0",
		"gateway_v4": "149.248.8.1",
		"plan": "vbm-4c-32gb",
		"v6_network": "2001:19f0:6001:775::",
		"v6_main_ip": "2001:19f0:6001:0775:0ec4:7aff:fe8f:679f",
		"v6_network_size": 64,
		"mac_address": 14038009341855,
		"label": "test-bm-tags",
		"tag": "test-tag",
		"os_id": 477,
		"app_id": 0,
		"image_id": "",
		"features": [
			"ipv6"
		],
		"tags": []
	}
	
#### With empty string
On node pools:

	np, err := client.Kubernetes.UpdateNodePool(ctx, clusterID, nodePoolID, &govultr.NodePoolReqUpdate{
		Tag: govultr.StringToStringPtr(""),
	})

Which generates this request body:

	{"tag":""}

And removes the tag on the node pool:

	{
		"id": "963a698c-1270-4411-ae19-af2fb0f17ccb",
		"date_created": "2022-05-16T19:31:11+00:00",
		"date_updated": "2022-05-17T13:47:04+00:00",
		"label": "np-tag-reset",
		"plan": "voc-c-2c-4gb-75s-amd",
		"status": "active",
		"node_quantity": 3,
		"min_nodes": 1,
		"max_nodes": 1,
		"auto_scaler": false,
		"tag": "",
		"nodes": [
			{
				"id": "af4830f3-1886-4434-ad12-43849e24b3a3",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-584bd1ebbf15",
				"status": "active"
			},
			{
				"id": "7c52abc0-5bcd-494f-ba54-b57989fbe1f5",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-90b3ae63f540",
				"status": "active"
			},
			{
				"id": "48b42054-d099-49e1-8900-b7e4ef46f976",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-e31a47a6fcd8",
				"status": "active"
			}
		]
	}

On instances:

	inst, err := client.Instance.Update(ctx, instID, &govultr.InstanceUpdateReq{
		Tag: govultr.StringToStringPtr(""),
	})

Which generates this request body:

	{"tag":"","tags":null,"ddos_protection":null}

And removes the tag:

	{
		"id": "9c89193b-21af-4269-9212-96d7acb19145",
		"os": "Debian 11 x64 (bullseye)",
		"ram": 1024,
		"disk": 0,
		"plan": "vc2-1c-1gb",
		"main_ip": "108.61.86.208",
		"vcpu_count": 1,
		"region": "ewr",
		"date_created": "2022-05-16T16:20:53+00:00",
		"status": "active",
		"allowed_bandwidth": 1000,
		"netmask_v4": "255.255.254.0",
		"gateway_v4": "108.61.86.1",
		"power_status": "running",
		"server_status": "ok",
		"v6_network": "",
		"v6_main_ip": "",
		"v6_network_size": 0,
		"label": "testest",
		"internal_ip": "",
		"kvm": "https://my.vultr.com/subs/vps/novnc/api.php?data=djJ8dVF2TEF6SUZGd2FYZnBRalkwV2tPam5oQk1rSjFKQmV8kV-Ofe4U6-tqKMpsdHYdWcbPTn_O_NP3cjOxdgWGYri3ppITVHqg54DzWjpj7mClzSf6VCjZ-qGRuNshzS7lJAFkUt1AypcKvDNXROfGTrqDFgxB26SbK285gwCKujdfcNXfV_UyKyReG_cl2PFE9mm5KCcFylBTXqDVOxJdbAJU9k-AoC7r7gxjIY2kTdEZrA5T-39QX9OY",
		"tag": "",
		"os_id": 477,
		"app_id": 0,
		"image_id": "",
		"firewall_group_id": "",
		"features": [],
		"hostname": "vultr.guest",
		"tags": []
	}

On **bare metal**:

	bm, err := client.BareMetalServer.Update(ctx, bmID, &govultr.BareMetalUpdate{
		Tag: govultr.StringToStringPtr(""),
	})

Which generates this request body:

	{"tag":"","tags":null}

And removes the tag as expected:

	{
		"id": "7ea675a7-db61-40cc-aa68-9135ead25352",
		"os": "Debian 11 x64 (bullseye)",
		"ram": "32768 MB",
		"disk": "2x 240GB SSD",
		"main_ip": "149.248.9.242",
		"cpu_count": 4,
		"region": "lax",
		"default_password": "",
		"date_created": "2022-05-17T14:10:02+00:00",
		"status": "active",
		"netmask_v4": "255.255.254.0",
		"gateway_v4": "149.248.8.1",
		"plan": "vbm-4c-32gb",
		"v6_network": "2001:19f0:6001:775::",
		"v6_main_ip": "2001:19f0:6001:0775:0ec4:7aff:fe8f:679f",
		"v6_network_size": 64,
		"mac_address": 14038009341855,
		"label": "test-bm-tags",
		"tag": "",
		"os_id": 477,
		"app_id": 0,
		"image_id": "",
		"features": [
			"ipv6"
		],
		"tags": []
	}

#### With an empty struct
On **node pools**:

	np, err := client.Kubernetes.UpdateNodePool(ctx, clusterID, nodePoolID, &govultr.NodePoolReqUpdate{})

Genereates an empty body:

	{}

And does nothing to the node pool:

	{
		"id": "963a698c-1270-4411-ae19-af2fb0f17ccb",
		"date_created": "2022-05-16T19:31:11+00:00",
		"date_updated": "2022-05-17T14:04:35+00:00",
		"label": "np-tag-reset",
		"plan": "voc-c-2c-4gb-75s-amd",
		"status": "active",
		"node_quantity": 3,
		"min_nodes": 1,
		"max_nodes": 1,
		"auto_scaler": false,
		"tag": "test-tag2",
		"nodes": [
			{
				"id": "af4830f3-1886-4434-ad12-43849e24b3a3",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-584bd1ebbf15",
				"status": "active"
			},
			{
				"id": "7c52abc0-5bcd-494f-ba54-b57989fbe1f5",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-90b3ae63f540",
				"status": "active"
			},
			{
				"id": "48b42054-d099-49e1-8900-b7e4ef46f976",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-e31a47a6fcd8",
				"status": "active"
			}
		]
	}

On **instances**:

	inst, err := client.Instance.Update(ctx, instID, &govultr.InstanceUpdateReq{})

Which generates this request body:

	{"tags":null,"ddos_protection":null}

And does not update the tag:

	{
		"id": "9c89193b-21af-4269-9212-96d7acb19145",
		"os": "Debian 11 x64 (bullseye)",
		"ram": 1024,
		"disk": 0,
		"plan": "vc2-1c-1gb",
		"main_ip": "108.61.86.208",
		"vcpu_count": 1,
		"region": "ewr",
		"date_created": "2022-05-16T16:20:53+00:00",
		"status": "active",
		"allowed_bandwidth": 1000,
		"netmask_v4": "255.255.254.0",
		"gateway_v4": "108.61.86.1",
		"power_status": "running",
		"server_status": "ok",
		"v6_network": "",
		"v6_main_ip": "",
		"v6_network_size": 0,
		"label": "testest",
		"internal_ip": "",
		"kvm": "https://my.vultr.com/subs/vps/novnc/api.php?data=djJ8dVF2TEF6SUZGd2FYZnBRalkwV2tPam5oQk1rSjFKQmV8kV-Ofe4U6-tqKMpsdHYdWcbPTn_O_NP3cjOxdgWGYri3ppITVHqg54DzWjpj7mClzSf6VCjZ-qGRuNshzS7lJAFkUt1AypcKvDNXROfGTrqDFgxB26SbK285gwCKujdfcNXfV_UyKyReG_cl2PFE9mm5KCcFylBTXqDVOxJdbAJU9k-AoC7r7gxjIY2kTdEZrA5T-39QX9OY",
		"tag": "test-tag2",
		"os_id": 477,
		"app_id": 0,
		"image_id": "",
		"firewall_group_id": "",
		"features": [],
		"hostname": "vultr.guest",
		"tags": []
	}

On **bare metal**:

	bm, err := client.BareMetalServer.Update(ctx, bmID, &govultr.BareMetalUpdate{})

Generates this body in the request:

	{"tags":null}

And does not affect the tag on the server:

	{
		"id": "7ea675a7-db61-40cc-aa68-9135ead25352",
		"os": "Debian 11 x64 (bullseye)",
		"ram": "32768 MB",
		"disk": "2x 240GB SSD",
		"main_ip": "149.248.9.242",
		"cpu_count": 4,
		"region": "lax",
		"default_password": "",
		"date_created": "2022-05-17T14:10:02+00:00",
		"status": "active",
		"netmask_v4": "255.255.254.0",
		"gateway_v4": "149.248.8.1",
		"plan": "vbm-4c-32gb",
		"v6_network": "2001:19f0:6001:775::",
		"v6_main_ip": "2001:19f0:6001:0775:0ec4:7aff:fe8f:679f",
		"v6_network_size": 64,
		"mac_address": 14038009341855,
		"label": "test-bm-tags",
		"tag": "test-tag2",
		"os_id": 477,
		"app_id": 0,
		"image_id": "",
		"features": [
			"ipv6"
		],
		"tags": []
	}

### `AutoScaler` on node pools
This is a `*boolean` which is also not set to `omitempty` in the updates.  To test:
* A `true` value should update to match
* A `false` value should update to match
* An empty struct (undefined value) should do nothing

#### With `true`

With:

	func vkeNodePoolUpdate(client *govultr.Client, ctx context.Context) {
		var clusterID string = "ec9c6ba7-5182-4fcd-8091-d5e65f677dfa"
		var nodePoolID string = "963a698c-1270-4411-ae19-af2fb0f17ccb"
		var autoScaler bool = true

		np, err := client.Kubernetes.UpdateNodePool(ctx, clusterID, nodePoolID, &govultr.NodePoolReqUpdate{
			AutoScaler:   &autoScaler,
		})

		if err != nil {
			fmt.Println(err)
			panic(err.Error())
		}

		printJson(np)
	}

Generates this for the request body:

	{"auto_scaler":true}

And results in this update:

	{
		"id": "963a698c-1270-4411-ae19-af2fb0f17ccb",
		"date_created": "2022-05-16T19:31:11+00:00",
		"date_updated": "2022-05-17T15:00:54+00:00",
		"label": "np-tag-reset",
		"plan": "voc-c-2c-4gb-75s-amd",
		"status": "active",
		"node_quantity": 3,
		"min_nodes": 1,
		"max_nodes": 1,
		"auto_scaler": true,
		"tag": "test-tag2",
		"nodes": [
			{
				"id": "af4830f3-1886-4434-ad12-43849e24b3a3",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-584bd1ebbf15",
				"status": "active"
			},
			{
				"id": "7c52abc0-5bcd-494f-ba54-b57989fbe1f5",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-90b3ae63f540",
				"status": "active"
			},
			{
				"id": "48b42054-d099-49e1-8900-b7e4ef46f976",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-e31a47a6fcd8",
				"status": "active"
			}
		]
	}

#### With `false`

With: 

	var autoScaler bool = false

	np, err := client.Kubernetes.UpdateNodePool(ctx, clusterID, nodePoolID, &govultr.NodePoolReqUpdate{
		AutoScaler:   &autoScaler,
	})

Generates this body:

	{"auto_scaler":false}

And results in the value set to `false`:

	{
		"id": "963a698c-1270-4411-ae19-af2fb0f17ccb",
		"date_created": "2022-05-16T19:31:11+00:00",
		"date_updated": "2022-05-17T15:04:20+00:00",
		"label": "np-tag-reset",
		"plan": "voc-c-2c-4gb-75s-amd",
		"status": "active",
		"node_quantity": 3,
		"min_nodes": 1,
		"max_nodes": 1,
		"auto_scaler": false,
		"tag": "test-tag2",
		"nodes": [
			{
				"id": "af4830f3-1886-4434-ad12-43849e24b3a3",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-584bd1ebbf15",
				"status": "active"
			},
			{
				"id": "7c52abc0-5bcd-494f-ba54-b57989fbe1f5",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-90b3ae63f540",
				"status": "active"
			},
			{
				"id": "48b42054-d099-49e1-8900-b7e4ef46f976",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-e31a47a6fcd8",
				"status": "active"
			}
		]
	}

#### Empty/Undefined

With:

	np, err := client.Kubernetes.UpdateNodePool(ctx, clusterID, nodePoolID, &govultr.NodePoolReqUpdate{})

Generates this body:

	{}

And results in a value of `true` remaining set:

	{
		"id": "963a698c-1270-4411-ae19-af2fb0f17ccb",
		"date_created": "2022-05-16T19:31:11+00:00",
		"date_updated": "2022-05-17T15:07:51+00:00",
		"label": "np-tag-reset",
		"plan": "voc-c-2c-4gb-75s-amd",
		"status": "active",
		"node_quantity": 3,
		"min_nodes": 1,
		"max_nodes": 1,
		"auto_scaler": true,
		"tag": "test-tag2",
		"nodes": [
			{
				"id": "af4830f3-1886-4434-ad12-43849e24b3a3",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-584bd1ebbf15",
				"status": "active"
			},
			{
				"id": "7c52abc0-5bcd-494f-ba54-b57989fbe1f5",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-90b3ae63f540",
				"status": "active"
			},
			{
				"id": "48b42054-d099-49e1-8900-b7e4ef46f976",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-e31a47a6fcd8",
				"status": "active"
			}
		]
	}

As well as a value of `false` remaining set:

	{
		"id": "963a698c-1270-4411-ae19-af2fb0f17ccb",
		"date_created": "2022-05-16T19:31:11+00:00",
		"date_updated": "2022-05-17T15:04:20+00:00",
		"label": "np-tag-reset",
		"plan": "voc-c-2c-4gb-75s-amd",
		"status": "active",
		"node_quantity": 3,
		"min_nodes": 1,
		"max_nodes": 1,
		"auto_scaler": false,
		"tag": "test-tag2",
		"nodes": [
			{
				"id": "af4830f3-1886-4434-ad12-43849e24b3a3",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-584bd1ebbf15",
				"status": "active"
			},
			{
				"id": "7c52abc0-5bcd-494f-ba54-b57989fbe1f5",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-90b3ae63f540",
				"status": "active"
			},
			{
				"id": "48b42054-d099-49e1-8900-b7e4ef46f976",
				"date_created": "2022-05-16T19:31:11+00:00",
				"label": "np-tag-reset-e31a47a6fcd8",
				"status": "active"
			}
		]
	}

**Review by ddymko — APPROVED** [review]
tested locally - looks good

**Pull request merged**
